export {default as aboutUs} from "./aboutUs"
export {default as browse} from "./browse"
export {default as contactUs} from "./contactUs"
export {default as home} from "./home"
export {default as orders} from "./orders"
